In [1]:
!pip install datasets pandas pymongo sentence_transformers

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.57.6)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (2.9.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence_transformers) (3.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 35.5 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 34.6 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0

In [2]:
!pip install -U transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.6)
Collecting transformers
  Downloading transformers-5.0.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Collecting huggingface-hub<2.0,>=1.3.0 (from transformers)
  Downloading huggingface_hub-1.3.4-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cu126)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Downloading transformers-5.0.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 85.1 MB/s eta 0:00:00
Downloading huggingface_hub-1.3.4-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.6/536.6 kB 30.1 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.36.0
    Uninstalling huggingface-hub-0.36.0:
      Successfully uninstalled huggingface-hub-0.36.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.6
    Uninstalling transformers-4.57.6:
      Successfully uninstalled transformers-4.57.6
Successfully installed huggingface-hub-1.3.4 transformers-5.0.0

In [3]:
from datasets import load_dataset

In [4]:
import pandas as pd
dataset=load_dataset("MongoDB/embedded_movies")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sample_mflix.embedded_movies.json:   0%|          | 0.00/42.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1500 [00:00<?, ? examples/s]

In [5]:
dataset

DatasetDict({
    train: Dataset({
        features: ['plot', 'runtime', 'genres', 'fullplot', 'directors', 'writers', 'countries', 'poster', 'languages', 'cast', 'title', 'num_mflix_comments', 'rated', 'imdb', 'awards', 'type', 'metacritic', 'plot_embedding'],
        num_rows: 1500
    })
})

In [6]:
dataset_df=pd.DataFrame(dataset['train'])

In [7]:
dataset_df.head()

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,plot_embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0007293965299999999, -0.026834568000000003,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.022837115, -0.022941574000000003, 0.014937..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.00023330492999999998, -0.028511643000000003..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.005927917, -0.033394486, 0.0015323418, -0...."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0059373598, -0.026604708, -0.0070914757000..."

In [8]:
dataset_df.shape

(1500, 18)

In [9]:
dataset_df['fullplot'].isnull().sum()

np.int64(48)

In [10]:
dataset_df=dataset_df.dropna(subset=['fullplot'])

In [11]:
dataset_df['fullplot'].isnull().sum()

np.int64(0)

In [12]:
dataset_df = dataset_df.drop(columns=["plot_embedding"])

In [13]:
from sentence_transformers import SentenceTransformer
embedding_model=SentenceTransformer("thenlper/gte-large")

modules.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/619 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/670M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertModel LOAD REPORT from: thenlper/gte-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/342 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [14]:
embedding_model.encode("Hi i am turjo")

array([-0.004986, -0.002384, -0.02965 , ..., -0.02116 , -0.009224,
       -0.03732 ], dtype=float16)

In [15]:
embedding_model.encode("Hi i am turjo").shape

(1024,)

In [16]:
def get_embedding(text:str)->list[float]:

  if not text.strip():
    print("attempted to get embedding for empty text.")
    return []

  embedding=embedding_model.encode(text)
  return embedding.tolist()

In [17]:
dataset_df["embedding"]=dataset_df["fullplot"].apply(get_embedding)

In [18]:
dataset_df.head(3)

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.0092620849609375, -0.00507354736328125, -0..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0024318695068359375, 0.0230712890625, -0.0..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.01219940185546875, -0.01146697998046875, -0..."

In [19]:
import pymongo

In [23]:

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://zahidulislamturjo_db_user:<password>.0jitwrn.mongodb.net/?appName=testCluster"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [24]:
# create / use database
db=client['mongoRag']

In [25]:
# create / use collection
collection=db['mongoragcollection']

In [26]:
# insert Data
collection.insert_one({
    "name": "Zahid",
    "role": "AI learner",
    "test": True
})

InsertOneResult(ObjectId('6978bd2196299e4e213f9de0'), acknowledged=True)

In [30]:
document=dataset_df.to_dict("records")

In [31]:
collection.insert_many(document)

InsertManyResult([ObjectId('6978bfc596299e4e213f9de1'), ObjectId('6978bfc596299e4e213f9de2'), ObjectId('6978bfc596299e4e213f9de3'), ObjectId('6978bfc596299e4e213f9de4'), ObjectId('6978bfc596299e4e213f9de5'), ObjectId('6978bfc596299e4e213f9de6'), ObjectId('6978bfc596299e4e213f9de7'), ObjectId('6978bfc596299e4e213f9de8'), ObjectId('6978bfc596299e4e213f9de9'), ObjectId('6978bfc596299e4e213f9dea'), ObjectId('6978bfc596299e4e213f9deb'), ObjectId('6978bfc596299e4e213f9dec'), ObjectId('6978bfc596299e4e213f9ded'), ObjectId('6978bfc596299e4e213f9dee'), ObjectId('6978bfc596299e4e213f9def'), ObjectId('6978bfc596299e4e213f9df0'), ObjectId('6978bfc596299e4e213f9df1'), ObjectId('6978bfc596299e4e213f9df2'), ObjectId('6978bfc596299e4e213f9df3'), ObjectId('6978bfc596299e4e213f9df4'), ObjectId('6978bfc596299e4e213f9df5'), ObjectId('6978bfc596299e4e213f9df6'), ObjectId('6978bfc596299e4e213f9df7'), ObjectId('6978bfc596299e4e213f9df8'), ObjectId('6978bfc596299e4e213f9df9'), ObjectId('6978bfc596299e4e213f9dfa'), ObjectId('6978bfc596299e4e213f9dfb'), ObjectId('6978bfc596299e4e213f9dfc'), ObjectId('6978bfc596299e4e213f9dfd'), ObjectId('6978bfc596299e4e213f9dfe'), ObjectId('6978bfc596299e4e213f9dff'), ObjectId('6978bfc596299e4e213f9e00'), ObjectId('6978bfc596299e4e213f9e01'), ObjectId('6978bfc596299e4e213f9e02'), ObjectId('6978bfc596299e4e213f9e03'), ObjectId('6978bfc596299e4e213f9e04'), ObjectId('6978bfc596299e4e213f9e05'), ObjectId('6978bfc596299e4e213f9e06'), ObjectId('6978bfc596299e4e213f9e07'), ObjectId('6978bfc596299e4e213f9e08'), ObjectId('6978bfc596299e4e213f9e09'), ObjectId('6978bfc596299e4e213f9e0a'), ObjectId('6978bfc596299e4e213f9e0b'), ObjectId('6978bfc596299e4e213f9e0c'), ObjectId('6978bfc596299e4e213f9e0d'), ObjectId('6978bfc596299e4e213f9e0e'), ObjectId('6978bfc596299e4e213f9e0f'), ObjectId('6978bfc596299e4e213f9e10'), ObjectId('6978bfc596299e4e213f9e11'), ObjectId('6978bfc596299e4e213f9e12'), ObjectId('6978bfc596299e4e213f9e13'), ObjectId('6978bfc596299e4e213f9e14'), ObjectId('6978bfc596299e4e213f9e15'), ObjectId('6978bfc596299e4e213f9e16'), ObjectId('6978bfc596299e4e213f9e17'), ObjectId('6978bfc596299e4e213f9e18'), ObjectId('6978bfc596299e4e213f9e19'), ObjectId('6978bfc596299e4e213f9e1a'), ObjectId('6978bfc596299e4e213f9e1b'), ObjectId('6978bfc596299e4e213f9e1c'), ObjectId('6978bfc596299e4e213f9e1d'), ObjectId('6978bfc596299e4e213f9e1e'), ObjectId('6978bfc596299e4e213f9e1f'), ObjectId('6978bfc596299e4e213f9e20'), ObjectId('6978bfc596299e4e213f9e21'), ObjectId('6978bfc596299e4e213f9e22'), ObjectId('6978bfc596299e4e213f9e23'), ObjectId('6978bfc596299e4e213f9e24'), ObjectId('6978bfc596299e4e213f9e25'), ObjectId('6978bfc596299e4e213f9e26'), ObjectId('6978bfc596299e4e213f9e27'), ObjectId('6978bfc596299e4e213f9e28'), ObjectId('6978bfc596299e4e213f9e29'), ObjectId('6978bfc596299e4e213f9e2a'), ObjectId('6978bfc596299e4e213f9e2b'), ObjectId('6978bfc596299e4e213f9e2c'), ObjectId('6978bfc596299e4e213f9e2d'), ObjectId('6978bfc596299e4e213f9e2e'), ObjectId('6978bfc596299e4e213f9e2f'), ObjectId('6978bfc596299e4e213f9e30'), ObjectId('6978bfc596299e4e213f9e31'), ObjectId('6978bfc596299e4e213f9e32'), ObjectId('6978bfc596299e4e213f9e33'), ObjectId('6978bfc596299e4e213f9e34'), ObjectId('6978bfc596299e4e213f9e35'), ObjectId('6978bfc596299e4e213f9e36'), ObjectId('6978bfc596299e4e213f9e37'), ObjectId('6978bfc596299e4e213f9e38'), ObjectId('6978bfc596299e4e213f9e39'), ObjectId('6978bfc596299e4e213f9e3a'), ObjectId('6978bfc596299e4e213f9e3b'), ObjectId('6978bfc596299e4e213f9e3c'), ObjectId('6978bfc596299e4e213f9e3d'), ObjectId('6978bfc596299e4e213f9e3e'), ObjectId('6978bfc596299e4e213f9e3f'), ObjectId('6978bfc596299e4e213f9e40'), ObjectId('6978bfc596299e4e213f9e41'), ObjectId('6978bfc596299e4e213f9e42'), ObjectId('6978bfc596299e4e213f9e43'), ObjectId('6978bfc596299e4e213f9e44'), ObjectId('6978bfc596299e4e213f9e45'), ObjectId('6978bfc596299e4e213f9e46'), ObjectId('6978bfc596299e4e213f9e47'), ObjectId('6978bfc596299e4e213f9e48'), ObjectId('6978bfc596299e4e213f9e49'), ObjectId('6978bfc596299e4e213f9e4a'), ObjectId('6978bfc596299e4e213f9e4b'), ObjectId('6978bfc596299e4e213f9e4c'), ObjectId('6978bfc596299e4e213f9e4d'), ObjectId('6978bfc596299e4e213f9e4e'), ObjectId('6978bfc596299e4e213f9e4f'), ObjectId('6978bfc596299e4e213f9e50'), ObjectId('6978bfc596299e4e213f9e51'), ObjectId('6978bfc596299e4e213f9e52'), ObjectId('6978bfc596299e4e213f9e53'), ObjectId('6978bfc596299e4e213f9e54'), ObjectId('6978bfc596299e4e213f9e55'), ObjectId('6978bfc596299e4e213f9e56'), ObjectId('6978bfc596299e4e213f9e57'), ObjectId('6978bfc596299e4e213f9e58'), ObjectId('6978bfc596299e4e213f9e59'), ObjectId('6978bfc596299e4e213f9e5a'), ObjectId('6978bfc596299e4e213f9e5b'), ObjectId('6978bfc596299e4e213f9e5c'), ObjectId('6978bfc596299e4e213f9e5d'), ObjectId('6978bfc596299e4e213f9e5e'), ObjectId('6978bfc596299e4e213f9e5f'), ObjectId('6978bfc596299e4e213f9e60'), ObjectId('6978bfc596299e4e213f9e61'), ObjectId('6978bfc596299e4e213f9e62'), ObjectId('6978bfc596299e4e213f9e63'), ObjectId('6978bfc596299e4e213f9e64'), ObjectId('6978bfc596299e4e213f9e65'), ObjectId('6978bfc596299e4e213f9e66'), ObjectId('6978bfc596299e4e213f9e67'), ObjectId('6978bfc596299e4e213f9e68'), ObjectId('6978bfc596299e4e213f9e69'), ObjectId('6978bfc596299e4e213f9e6a'), ObjectId('6978bfc596299e4e213f9e6b'), ObjectId('6978bfc596299e4e213f9e6c'), ObjectId('6978bfc596299e4e213f9e6d'), ObjectId('6978bfc596299e4e213f9e6e'), ObjectId('6978bfc596299e4e213f9e6f'), ObjectId('6978bfc596299e4e213f9e70'), ObjectId('6978bfc596299e4e213f9e71'), ObjectId('6978bfc596299e4e213f9e72'), ObjectId('6978bfc596299e4e213f9e73'), ObjectId('6978bfc596299e4e213f9e74'), ObjectId('6978bfc596299e4e213f9e75'), ObjectId('6978bfc596299e4e213f9e76'), ObjectId('6978bfc596299e4e213f9e77'), ObjectId('6978bfc596299e4e213f9e78'), ObjectId('6978bfc596299e4e213f9e79'), ObjectId('6978bfc596299e4e213f9e7a'), ObjectId('6978bfc596299e4e213f9e7b'), ObjectId('6978bfc596299e4e213f9e7c'), ObjectId('6978bfc596299e4e213f9e7d'), ObjectId('6978bfc596299e4e213f9e7e'), ObjectId('6978bfc596299e4e213f9e7f'), ObjectId('6978bfc596299e4e213f9e80'), ObjectId('6978bfc596299e4e213f9e81'), ObjectId('6978bfc596299e4e213f9e82'), ObjectId('6978bfc596299e4e213f9e83'), ObjectId('6978bfc596299e4e213f9e84'), ObjectId('6978bfc596299e4e213f9e85'), ObjectId('6978bfc596299e4e213f9e86'), ObjectId('6978bfc596299e4e213f9e87'), ObjectId('6978bfc596299e4e213f9e88'), ObjectId('6978bfc596299e4e213f9e89'), ObjectId('6978bfc596299e4e213f9e8a'), ObjectId('6978bfc596299e4e213f9e8b'), ObjectId('6978bfc596299e4e213f9e8c'), ObjectId('6978bfc596299e4e213f9e8d'), ObjectId('6978bfc596299e4e213f9e8e'), ObjectId('6978bfc596299e4e213f9e8f'), ObjectId('6978bfc596299e4e213f9e90'), ObjectId('6978bfc596299e4e213f9e91'), ObjectId('6978bfc596299e4e213f9e92'), ObjectId('6978bfc596299e4e213f9e93'), ObjectId('6978bfc596299e4e213f9e94'), ObjectId('6978bfc596299e4e213f9e95'), ObjectId('6978bfc596299e4e213f9e96'), ObjectId('6978bfc596299e4e213f9e97'), ObjectId('6978bfc596299e4e213f9e98'), ObjectId('6978bfc596299e4e213f9e99'), ObjectId('6978bfc596299e4e213f9e9a'), ObjectId('6978bfc596299e4e213f9e9b'), ObjectId('6978bfc596299e4e213f9e9c'), ObjectId('6978bfc596299e4e213f9e9d'), ObjectId('6978bfc596299e4e213f9e9e'), ObjectId('6978bfc596299e4e213f9e9f'), ObjectId('6978bfc596299e4e213f9ea0'), ObjectId('6978bfc596299e4e213f9ea1'), ObjectId('6978bfc596299e4e213f9ea2'), ObjectId('6978bfc596299e4e213f9ea3'), ObjectId('6978bfc596299e4e213f9ea4'), ObjectId('6978bfc596299e4e213f9ea5'), ObjectId('6978bfc596299e4e213f9ea6'), ObjectId('6978bfc596299e4e213f9ea7'), ObjectId('6978bfc596299e4e213f9ea8'), ObjectId('6978bfc596299e4e213f9ea9'), ObjectId('6978bfc596299e4e213f9eaa'), ObjectId('6978bfc596299e4e213f9eab'), ObjectId('6978bfc596299e4e213f9eac'), ObjectId('6978bfc596299e4e213f9ead'), ObjectId('6978bfc596299e4e213f9eae'), ObjectId('6978bfc596299e4e213f9eaf'), ObjectId('6978bfc596299e4e213f9eb0'), ObjectId('6978bfc596299e4e213f9eb1'), ObjectId('6978bfc596299e4e213f9eb2'), ObjectId('6978bfc596299e4e213f9eb3'), ObjectId('6978bfc596299e4e213f9eb4'), ObjectId('6978bfc596299e4e213f9eb5'), ObjectId('6978bfc596299e4e213f9eb6'), ObjectId('6978bfc596299e4e213f9eb7'), ObjectId('6978bfc596299e4e213f9eb8'), ObjectId('6978bfc596299e4e213f9eb9'), ObjectId('6978bfc596299e4e213f9eba'), ObjectId('6978bfc596299e4e213f9ebb'), ObjectId('6978bfc596299e4e213f9ebc'), ObjectId('6978bfc596299e4e213f9ebd'), ObjectId('6978bfc596299e4e213f9ebe'), ObjectId('6978bfc596299e4e213f9ebf'), ObjectId('6978bfc596299e4e213f9ec0'), ObjectId('6978bfc596299e4e213f9ec1'), ObjectId('6978bfc596299e4e213f9ec2'), ObjectId('6978bfc596299e4e213f9ec3'), ObjectId('6978bfc596299e4e213f9ec4'), ObjectId('6978bfc596299e4e213f9ec5'), ObjectId('6978bfc596299e4e213f9ec6'), ObjectId('6978bfc596299e4e213f9ec7'), ObjectId('6978bfc596299e4e213f9ec8'), ObjectId('6978bfc596299e4e213f9ec9'), ObjectId('6978bfc596299e4e213f9eca'), ObjectId('6978bfc596299e4e213f9ecb'), ObjectId('6978bfc596299e4e213f9ecc'), ObjectId('6978bfc596299e4e213f9ecd'), ObjectId('6978bfc596299e4e213f9ece'), ObjectId('6978bfc596299e4e213f9ecf'), ObjectId('6978bfc596299e4e213f9ed0'), ObjectId('6978bfc596299e4e213f9ed1'), ObjectId('6978bfc596299e4e213f9ed2'), ObjectId('6978bfc596299e4e213f9ed3'), ObjectId('6978bfc596299e4e213f9ed4'), ObjectId('6978bfc596299e4e213f9ed5'), ObjectId('6978bfc596299e4e213f9ed6'), ObjectId('6978bfc596299e4e213f9ed7'), ObjectId('6978bfc596299e4e213f9ed8'), ObjectId('6978bfc596299e4e213f9ed9'), ObjectId('6978bfc596299e4e213f9eda'), ObjectId('6978bfc596299e4e213f9edb'), ObjectId('6978bfc596299e4e213f9edc'), ObjectId('6978bfc596299e4e213f9edd'), ObjectId('6978bfc596299e4e213f9ede'), ObjectId('6978bfc596299e4e213f9edf'), ObjectId('6978bfc596299e4e213f9ee0'), ObjectId('6978bfc596299e4e213f9ee1'), ObjectId('6978bfc596299e4e213f9ee2'), ObjectId('6978bfc596299e4e213f9ee3'), ObjectId('6978bfc596299e4e213f9ee4'), ObjectId('6978bfc596299e4e213f9ee5'), ObjectId('6978bfc596299e4e213f9ee6'), ObjectId('6978bfc596299e4e213f9ee7'), ObjectId('6978bfc596299e4e213f9ee8'), ObjectId('6978bfc596299e4e213f9ee9'), ObjectId('6978bfc596299e4e213f9eea'), ObjectId('6978bfc596299e4e213f9eeb'), ObjectId('6978bfc596299e4e213f9eec'), ObjectId('6978bfc596299e4e213f9eed'), ObjectId('6978bfc596299e4e213f9eee'), ObjectId('6978bfc596299e4e213f9eef'), ObjectId('6978bfc596299e4e213f9ef0'), ObjectId('6978bfc596299e4e213f9ef1'), ObjectId('6978bfc596299e4e213f9ef2'), ObjectId('6978bfc596299e4e213f9ef3'), ObjectId('6978bfc596299e4e213f9ef4'), ObjectId('6978bfc596299e4e213f9ef5'), ObjectId('6978bfc596299e4e213f9ef6'), ObjectId('6978bfc596299e4e213f9ef7'), ObjectId('6978bfc596299e4e213f9ef8'), ObjectId('6978bfc596299e4e213f9ef9'), ObjectId('6978bfc596299e4e213f9efa'), ObjectId('6978bfc596299e4e213f9efb'), ObjectId('6978bfc596299e4e213f9efc'), ObjectId('6978bfc596299e4e213f9efd'), ObjectId('6978bfc596299e4e213f9efe'), ObjectId('6978bfc596299e4e213f9eff'), ObjectId('6978bfc596299e4e213f9f00'), ObjectId('6978bfc596299e4e213f9f01'), ObjectId('6978bfc596299e4e213f9f02'), ObjectId('6978bfc596299e4e213f9f03'), ObjectId('6978bfc596299e4e213f9f04'), ObjectId('6978bfc596299e4e213f9f05'), ObjectId('6978bfc596299e4e213f9f06'), ObjectId('6978bfc596299e4e213f9f07'), ObjectId('6978bfc596299e4e213f9f08'), ObjectId('6978bfc596299e4e213f9f09'), ObjectId('6978bfc596299e4e213f9f0a'), ObjectId('6978bfc596299e4e213f9f0b'), ObjectId('6978bfc596299e4e213f9f0c'), ObjectId('6978bfc596299e4e213f9f0d'), ObjectId('6978bfc596299e4e213f9f0e'), ObjectId('6978bfc596299e4e213f9f0f'), ObjectId('6978bfc596299e4e213f9f10'), ObjectId('6978bfc596299e4e213f9f11'), ObjectId('6978bfc596299e4e213f9f12'), ObjectId('6978bfc596299e4e213f9f13'), ObjectId('6978bfc596299e4e213f9f14'), ObjectId('6978bfc596299e4e213f9f15'), ObjectId('6978bfc596299e4e213f9f16'), ObjectId('6978bfc596299e4e213f9f17'), ObjectId('6978bfc596299e4e213f9f18'), ObjectId('6978bfc596299e4e213f9f19'), ObjectId('6978bfc596299e4e213f9f1a'), ObjectId('6978bfc596299e4e213f9f1b'), ObjectId('6978bfc596299e4e213f9f1c'), ObjectId('6978bfc596299e4e213f9f1d'), ObjectId('6978bfc596299e4e213f9f1e'), ObjectId('6978bfc596299e4e213f9f1f'), ObjectId('6978bfc596299e4e213f9f20'), ObjectId('6978bfc596299e4e213f9f21'), ObjectId('6978bfc596299e4e213f9f22'), ObjectId('6978bfc596299e4e213f9f23'), ObjectId('6978bfc596299e4e213f9f24'), ObjectId('6978bfc596299e4e213f9f25'), ObjectId('6978bfc596299e4e213f9f26'), ObjectId('6978bfc596299e4e213f9f27'), ObjectId('6978bfc596299e4e213f9f28'), ObjectId('6978bfc596299e4e213f9f29'), ObjectId('6978bfc596299e4e213f9f2a'), ObjectId('6978bfc596299e4e213f9f2b'), ObjectId('6978bfc596299e4e213f9f2c'), ObjectId('6978bfc596299e4e213f9f2d'), ObjectId('6978bfc596299e4e213f9f2e'), ObjectId('6978bfc596299e4e213f9f2f'), ObjectId('6978bfc596299e4e213f9f30'), ObjectId('6978bfc596299e4e213f9f31'), ObjectId('6978bfc596299e4e213f9f32'), ObjectId('6978bfc596299e4e213f9f33'), ObjectId('6978bfc596299e4e213f9f34'), ObjectId('6978bfc596299e4e213f9f35'), ObjectId('6978bfc596299e4e213f9f36'), ObjectId('6978bfc596299e4e213f9f37'), ObjectId('6978bfc596299e4e213f9f38'), ObjectId('6978bfc596299e4e213f9f39'), ObjectId('6978bfc596299e4e213f9f3a'), ObjectId('6978bfc596299e4e213f9f3b'), ObjectId('6978bfc596299e4e213f9f3c'), ObjectId('6978bfc596299e4e213f9f3d'), ObjectId('6978bfc596299e4e213f9f3e'), ObjectId('6978bfc596299e4e213f9f3f'), ObjectId('6978bfc596299e4e213f9f40'), ObjectId('6978bfc596299e4e213f9f41'), ObjectId('6978bfc596299e4e213f9f42'), ObjectId('6978bfc596299e4e213f9f43'), ObjectId('6978bfc596299e4e213f9f44'), ObjectId('6978bfc596299e4e213f9f45'), ObjectId('6978bfc596299e4e213f9f46'), ObjectId('6978bfc596299e4e213f9f47'), ObjectId('6978bfc596299e4e213f9f48'), ObjectId('6978bfc596299e4e213f9f49'), ObjectId('6978bfc596299e4e213f9f4a'), ObjectId('6978bfc596299e4e213f9f4b'), ObjectId('6978bfc596299e4e213f9f4c'), ObjectId('6978bfc596299e4e213f9f4d'), ObjectId('6978bfc596299e4e213f9f4e'), ObjectId('6978bfc596299e4e213f9f4f'), ObjectId('6978bfc596299e4e213f9f50'), ObjectId('6978bfc596299e4e213f9f51'), ObjectId('6978bfc596299e4e213f9f52'), ObjectId('6978bfc596299e4e213f9f53'), ObjectId('6978bfc596299e4e213f9f54'), ObjectId('6978bfc596299e4e213f9f55'), ObjectId('6978bfc596299e4e213f9f56'), ObjectId('6978bfc596299e4e213f9f57'), ObjectId('6978bfc596299e4e213f9f58'), ObjectId('6978bfc596299e4e213f9f59'), ObjectId('6978bfc596299e4e213f9f5a'), ObjectId('6978bfc596299e4e213f9f5b'), ObjectId('6978bfc596299e4e213f9f5c'), ObjectId('6978bfc596299e4e213f9f5d'), ObjectId('6978bfc596299e4e213f9f5e'), ObjectId('6978bfc596299e4e213f9f5f'), ObjectId('6978bfc596299e4e213f9f60'), ObjectId('6978bfc596299e4e213f9f61'), ObjectId('6978bfc596299e4e213f9f62'), ObjectId('6978bfc596299e4e213f9f63'), ObjectId('6978bfc596299e4e213f9f64'), ObjectId('6978bfc596299e4e213f9f65'), ObjectId('6978bfc596299e4e213f9f66'), ObjectId('6978bfc596299e4e213f9f67'), ObjectId('6978bfc596299e4e213f9f68'), ObjectId('6978bfc596299e4e213f9f69'), ObjectId('6978bfc596299e4e213f9f6a'), ObjectId('6978bfc596299e4e213f9f6b'), ObjectId('6978bfc596299e4e213f9f6c'), ObjectId('6978bfc596299e4e213f9f6d'), ObjectId('6978bfc596299e4e213f9f6e'), ObjectId('6978bfc596299e4e213f9f6f'), ObjectId('6978bfc596299e4e213f9f70'), ObjectId('6978bfc596299e4e213f9f71'), ObjectId('6978bfc596299e4e213f9f72'), ObjectId('6978bfc596299e4e213f9f73'), ObjectId('6978bfc596299e4e213f9f74'), ObjectId('6978bfc596299e4e213f9f75'), ObjectId('6978bfc596299e4e213f9f76'), ObjectId('6978bfc596299e4e213f9f77'), ObjectId('6978bfc596299e4e213f9f78'), ObjectId('6978bfc596299e4e213f9f79'), ObjectId('6978bfc596299e4e213f9f7a'), ObjectId('6978bfc596299e4e213f9f7b'), ObjectId('6978bfc596299e4e213f9f7c'), ObjectId('6978bfc596299e4e213f9f7d'), ObjectId('6978bfc596299e4e213f9f7e'), ObjectId('6978bfc596299e4e213f9f7f'), ObjectId('6978bfc596299e4e213f9f80'), ObjectId('6978bfc596299e4e213f9f81'), ObjectId('6978bfc596299e4e213f9f82'), ObjectId('6978bfc596299e4e213f9f83'), ObjectId('6978bfc596299e4e213f9f84'), ObjectId('6978bfc596299e4e213f9f85'), ObjectId('6978bfc596299e4e213f9f86'), ObjectId('6978bfc596299e4e213f9f87'), ObjectId('6978bfc596299e4e213f9f88'), ObjectId('6978bfc596299e4e213f9f89'), ObjectId('6978bfc596299e4e213f9f8a'), ObjectId('6978bfc596299e4e213f9f8b'), ObjectId('6978bfc596299e4e213f9f8c'), ObjectId('6978bfc596299e4e213f9f8d'), ObjectId('6978bfc596299e4e213f9f8e'), ObjectId('6978bfc596299e4e213f9f8f'), ObjectId('6978bfc596299e4e213f9f90'), ObjectId('6978bfc596299e4e213f9f91'), ObjectId('6978bfc596299e4e213f9f92'), ObjectId('6978bfc596299e4e213f9f93'), ObjectId('6978bfc596299e4e213f9f94'), ObjectId('6978bfc596299e4e213f9f95'), ObjectId('6978bfc596299e4e213f9f96'), ObjectId('6978bfc596299e4e213f9f97'), ObjectId('6978bfc596299e4e213f9f98'), ObjectId('6978bfc596299e4e213f9f99'), ObjectId('6978bfc596299e4e213f9f9a'), ObjectId('6978bfc596299e4e213f9f9b'), ObjectId('6978bfc596299e4e213f9f9c'), ObjectId('6978bfc596299e4e213f9f9d'), ObjectId('6978bfc596299e4e213f9f9e'), ObjectId('6978bfc596299e4e213f9f9f'), ObjectId('6978bfc596299e4e213f9fa0'), ObjectId('6978bfc596299e4e213f9fa1'), ObjectId('6978bfc596299e4e213f9fa2'), ObjectId('6978bfc596299e4e213f9fa3'), ObjectId('6978bfc596299e4e213f9fa4'), ObjectId('6978bfc596299e4e213f9fa5'), ObjectId('6978bfc596299e4e213f9fa6'), ObjectId('6978bfc596299e4e213f9fa7'), ObjectId('6978bfc596299e4e213f9fa8'), ObjectId('6978bfc596299e4e213f9fa9'), ObjectId('6978bfc596299e4e213f9faa'), ObjectId('6978bfc596299e4e213f9fab'), ObjectId('6978bfc596299e4e213f9fac'), ObjectId('6978bfc596299e4e213f9fad'), ObjectId('6978bfc596299e4e213f9fae'), ObjectId('6978bfc596299e4e213f9faf'), ObjectId('6978bfc596299e4e213f9fb0'), ObjectId('6978bfc596299e4e213f9fb1'), ObjectId('6978bfc596299e4e213f9fb2'), ObjectId('6978bfc596299e4e213f9fb3'), ObjectId('6978bfc596299e4e213f9fb4'), ObjectId('6978bfc596299e4e213f9fb5'), ObjectId('6978bfc596299e4e213f9fb6'), ObjectId('6978bfc596299e4e213f9fb7'), ObjectId('6978bfc596299e4e213f9fb8'), ObjectId('6978bfc596299e4e213f9fb9'), ObjectId('6978bfc596299e4e213f9fba'), ObjectId('6978bfc596299e4e213f9fbb'), ObjectId('6978bfc596299e4e213f9fbc'), ObjectId('6978bfc596299e4e213f9fbd'), ObjectId('6978bfc596299e4e213f9fbe'), ObjectId('6978bfc596299e4e213f9fbf'), ObjectId('6978bfc596299e4e213f9fc0'), ObjectId('6978bfc596299e4e213f9fc1'), ObjectId('6978bfc596299e4e213f9fc2'), ObjectId('6978bfc596299e4e213f9fc3'), ObjectId('6978bfc596299e4e213f9fc4'), ObjectId('6978bfc596299e4e213f9fc5'), ObjectId('6978bfc596299e4e213f9fc6'), ObjectId('6978bfc596299e4e213f9fc7'), ObjectId('6978bfc596299e4e213f9fc8'), ObjectId('6978bfc596299e4e213f9fc9'), ObjectId('6978bfc596299e4e213f9fca'), ObjectId('6978bfc596299e4e213f9fcb'), ObjectId('6978bfc596299e4e213f9fcc'), ObjectId('6978bfc596299e4e213f9fcd'), ObjectId('6978bfc596299e4e213f9fce'), ObjectId('6978bfc596299e4e213f9fcf'), ObjectId('6978bfc596299e4e213f9fd0'), ObjectId('6978bfc596299e4e213f9fd1'), ObjectId('6978bfc596299e4e213f9fd2'), ObjectId('6978bfc596299e4e213f9fd3'), ObjectId('6978bfc596299e4e213f9fd4'), ObjectId('6978bfc596299e4e213f9fd5'), ObjectId('6978bfc596299e4e213f9fd6'), ObjectId('6978bfc596299e4e213f9fd7'), ObjectId('6978bfc596299e4e213f9fd8'), ObjectId('6978bfc596299e4e213f9fd9'), ObjectId('6978bfc596299e4e213f9fda'), ObjectId('6978bfc596299e4e213f9fdb'), ObjectId('6978bfc596299e4e213f9fdc'), ObjectId('6978bfc596299e4e213f9fdd'), ObjectId('6978bfc596299e4e213f9fde'), ObjectId('6978bfc596299e4e213f9fdf'), ObjectId('6978bfc596299e4e213f9fe0'), ObjectId('6978bfc596299e4e213f9fe1'), ObjectId('6978bfc596299e4e213f9fe2'), ObjectId('6978bfc596299e4e213f9fe3'), ObjectId('6978bfc596299e4e213f9fe4'), ObjectId('6978bfc596299e4e213f9fe5'), ObjectId('6978bfc596299e4e213f9fe6'), ObjectId('6978bfc596299e4e213f9fe7'), ObjectId('6978bfc596299e4e213f9fe8'), ObjectId('6978bfc596299e4e213f9fe9'), ObjectId('6978bfc596299e4e213f9fea'), ObjectId('6978bfc596299e4e213f9feb'), ObjectId('6978bfc596299e4e213f9fec'), ObjectId('6978bfc596299e4e213f9fed'), ObjectId('6978bfc596299e4e213f9f

## Data Retrival

In [32]:
user_query="what is the best horror movie?"
query_embedding=get_embedding(user_query)

In [34]:
len(query_embedding)

1024

In [35]:
pipeline = [

    {
        "$vectorSearch": {
            "index": "vector_index",
            "queryVector": query_embedding,
            "path": "embedding",
            "numCandidates": 150,  # Number of candidate matches to consider
            "limit": 4,  # Return top 4 matches
        }
    },
    {
        "$project": {
            "fullplot": 1,  # Include the plot field
            "title": 1,  # Include the title field
            "genres": 1,  # Include the genres field
            "score": {"$meta": "vectorSearchScore"},  # Include the search score
        }
    }
]

In [36]:
collection.aggregate(pipeline)

In [37]:
list(collection.aggregate(pipeline))

[{'_id': ObjectId('6978bfc596299e4e213f9fdc'),
  'genres': ['Action', 'Horror', 'Thriller'],
  'fullplot': 'The "sematary" is up to its old zombie-raising tricks again. This time, the protagonists are Jeff Matthews, whose mother died in a Hollywood stage accident, and Drew Gilbert, a boy coping with an abusive stepfather.',
  'title': 'Pet Sematary II',
  'score': 0.9101011753082275},
 {'_id': ObjectId('6978bfc596299e4e213fa225'),
  'genres': ['Action', 'Horror'],
  'fullplot': 'This film is a prequel to all of the The House of the Dead video games. Set on an island off the coast, a techno rave party attracts a diverse group of college coeds and a Coast Guard officer. Soon, they discover that their X-laced escapades are to be interrupted by zombies and monsters that attack them on the ground, from the air, and in the sea, ruled by an evil entity in the House of the Dead...',
  'title': 'House of the Dead',
  'score': 0.9023181200027466},
 {'_id': ObjectId('6978bfc596299e4e213fa34f'),
  'genres': ['Action', 'Horror', 'Thriller'],
  'fullplot': 'A double-bill of thrillers that recall both filmmakers\' favorite exploitation films. "Grindhouse" (a downtown movie theater in disrepair since its glory days as a movie palace known for "grinding out" non-stop double-bill programs of B-movies) is presented as one full-length feature comprised of two individual films helmed separately by each director. "Death Proof," is a rip-roaring slasher flick where the killer pursues his victims with a car rather than a knife, while "Planet Terror" shows us a view of the world in the midst of a zombie outbreak. The films are joined together by clever faux trailers that recall the \'50s exploitation drive-in classics.',
  'title': 'Grindhouse',
  'score': 0.901063084602356},
 {'_id': ObjectId('6978bfc596299e4e213fa277'),
  'genres': ['Action', 'Horror', 'Sci-Fi'],
  'fullplot': 'Ana, a young beautiful nurse finishes her day-shift at the hospital to return home to her beloved husband, they make love and sleep together. The next day, after her husband is killed by her neighbor next door, he suddenly comes back to life. She discovers the chaos happening in her neighborhood and escapes from her home. Soon after coming to her senses in the woods, she encounters a cop and other survivors, they decide to find safety in a mall. Soon more survivors come, and they learn that if they want to stay alive, they should stick together as the world is overrun by an army of undead. Can they survive the horror in this horrific global chaos? When there is no more room in hell, the dead will walk the earth',
  'title': 'Dawn of the Dead',
  'score': 0.8991680145263672}]

In [38]:
def vector_search(user_query,collection):

  query_embedding=get_embedding(user_query)
  print(query_embedding)

  if query_embedding is None:
    return "Invalid query or embeddig is failed"

  pipeline=[

            {
                "$vectorSearch":{

                "index": "vector_index",
                "queryVector": query_embedding,
                "path": "embedding",
                "numCandidates": 150,  # Number of candidate matches to consider
                "limit": 4,  # Return top 4 matches


                }

            },

              {
                 "$project":{

                "fullplot": 1,  # Include the plot field
                "title": 1,  # Include the title field
                "genres": 1,  # Include the genres field
                "score": {"$meta": "vectorSearchScore"},  # Include the search score
                 }

            }

           ]

  result=collection.aggregate(pipeline)
  return list(result)

In [40]:
# vector_search("what is the best horror movie to watch and why?",collection)

In [41]:
def get_search_result(query,collection):

  get_knowledge=vector_search(query,collection)

  search_result=""

  for result in get_knowledge:
        search_result += f"Title: {result.get('title', 'N/A')}, Plot: {result.get('fullplot', 'N/A')}\n"

  return search_result

In [42]:
query="what is the best comedy movie to watch and why?"

In [43]:
source_information=get_search_result(query,collection)

[0.0196533203125, -0.0235443115234375, -0.031494140625, 0.01496124267578125, -0.016357421875, -0.0169219970703125, -0.01194000244140625, 0.041595458984375, -0.01336669921875, 0.0443115234375, 0.004589080810546875, 0.010528564453125, 0.01275634765625, -0.048309326171875, 0.005611419677734375, -0.031402587890625, -0.037567138671875, -0.0372314453125, -0.02972412109375, 0.0193634033203125, 0.004505157470703125, 0.016571044921875, -0.034332275390625, -0.009307861328125, 0.00824737548828125, 0.02032470703125, -0.00949859619140625, 0.0005860328674316406, 0.052001953125, 0.07379150390625, 0.01299285888671875, -0.05584716796875, 0.0189666748046875, -0.060791015625, 0.01114654541015625, -0.03326416015625, 0.0263519287109375, 0.01849365234375, -0.01171875, -0.045074462890625, -0.036102294921875, -0.0212860107421875, 0.03857421875, -0.0277099609375, -0.05560302734375, 0.0016002655029296875, 0.01348876953125, -0.0239105224609375, -0.00798797607421875, -0.021820068359375, 0.01207733154296875, -0.03045654296875, 0.0290069580078125, -0.00501251220703125, 0.01568603515625, 0.012725830078125, 0.003406524658203125, -0.0052032470703125, 0.0031986236572265625, 0.0125579833984375, 0.0295257568359375, -0.0109405517578125, 0.005084991455078125, -0.02178955078125, 0.05145263671875, 0.0156402587890625, 0.021148681640625, 0.0032482147216796875, 0.05364990234375, 0.0241546630859375, 0.007175445556640625, 1.8358230590820312e-05, 0.0032196044921875, -0.03790283203125, 0.005626678466796875, 0.002605438232421875, -0.0109100341796875, 0.03887939453125, -0.042877197265625, -0.00447845458984375, 0.0294342041015625, 0.0697021484375, 0.0155029296875, 0.0173797607421875, -0.067626953125, -0.04791259765625, 0.0206298828125, 0.049957275390625, -0.0184478759765625, 0.0201568603515625, 0.018341064453125, 0.0172271728515625, -0.0018739700317382812, -0.01557159423828125, 0.04107666015625, 0.0251922607421875, -0.04913330078125, 0.01922607421875, 0.01448822021484375, 0.0044708251953125, 0.00661468505859375, 0.03570556640625, -0.033294677734375, 0.016448974609375, -0.024810791015625, 0.0098876953125, 0.0238189697265625, 0.004108428955078125, -0.0305328369140625, -0.030731201171875, -0.0017070770263671875, 0.00432586669921875, 0.01122283935546875, 0.01125335693359375, -0.03204345703125, 0.0125732421875, 0.004428863525390625, 0.08636474609375, -0.041046142578125, 0.01195526123046875, 0.005954742431640625, 0.0273284912109375, 0.05291748046875, -0.02508544921875, 0.039825439453125, -0.027801513671875, -0.0214996337890625, 0.0308685302734375, -0.0146484375, -0.002735137939453125, 0.01220703125, -0.025909423828125, -0.0062103271484375, 0.045257568359375, -0.027679443359375, 0.008941650390625, -0.0212249755859375, 0.02191162109375, 0.0177154541015625, -0.041229248046875, 0.055511474609375, 0.034332275390625, -0.01165771484375, 0.08306884765625, 0.01442718505859375, 0.00849151611328125, 0.0011844635009765625, -0.026336669921875, 0.0139923095703125, 0.035400390625, -0.0211029052734375, 0.0201416015625, 0.00711822509765625, 0.00841522216796875, -0.0191497802734375, -0.012115478515625, -0.01352691650390625, 0.0125732421875, 0.055999755859375, 0.0570068359375, 0.01641845703125, 0.0011806488037109375, -0.0421142578125, 0.0714111328125, -0.001499176025390625, 0.0479736328125, -0.03692626953125, 0.00018465518951416016, -0.0257568359375, -0.00539398193359375, 0.00984954833984375, -0.002231597900390625, -0.01210784912109375, 0.0076751708984375, 0.0223846435546875, 0.052520751953125, 0.04736328125, -0.0548095703125, 0.0310516357421875, 0.01215362548828125, -0.03265380859375, -0.00939178466796875, -0.047119140625, 0.059844970703125, -0.020111083984375, -0.01303863525390625, -0.0004954338073730469, -0.038909912109375, -0.06298828125, -0.0285797119140625, -0.038909912109375, -0.0183563232421875, -0.0185394287109375, 0.035430908203125, 0.0221710205078125, 0.0182952880859375, -0.019561767578125, -0.0156707763671875, -0.0115203857421875, -0.05596923828125, -0.0208740234375, 0.063720703125, -0.02398681640625, -0.0008640289306640625, -0.006732940673828125, -0.039703369140625, 0.02630615234375, 0.083740234375, -0.06024169921875, -0.01345062255859375, 0.03173828125, 0.03558349609375, -0.01207733154296875, -0.0164794921875, -0.0021305084228515625, 0.0015687942504882812, -0.006439208984375, 0.0367431640625, -0.0207366943359375, 0.029296875, 0.00351715087890625, 0.0044097900390625, 0.024932861328125, 0.03179931640625, 0.006427764892578125, -0.0094757080078125, -0.0135040283203125, 0.012969970703125, -0.04205322265625, 0.01009368896484375, -0.0118408203125, 0.04815673828125, 0.0166015625, 0.050048828125, 0.0343017578125, 0.0065155029296875, 0.07598876953125, 0.034210205078125, -0.002841949462890625, 0.03704833984375, -0.0186767578125, 0.0134429931640625, 0.0323486328125, 0.035980224609375, -0.012115478515625, 0.01019287109375, 0.013031005859375, 0.00254058837890625, 0.0018358230590820312, 0.038055419921875, 0.0241546630859375, 0.026611328125, 0.028411865234375, 0.045562744140625, -0.006107330322265625, 0.04144287109375, 0.052764892578125, 0.0771484375, -0.00264739990234375, -0.00545501708984375, -0.0338134765625, 0.025390625, 0.03240966796875, -0.0029430389404296875, 0.0263824462890625, -0.02349853515625, -0.03741455078125, 0.060211181640625, -0.05108642578125, -0.06500244140625, -0.0233917236328125, -0.049560546875, -0.02069091796875, -0.0787353515625, -0.036285400390625, -0.009857177734375, 0.0256805419921875, -0.0287322998046875, 0.023040771484375, -0.01387786865234375, -0.0164947509765625, -0.00644683837890625, -0.01386260986328125, 0.04241943359375, 0.01499176025390625, 0.04022216796875, -0.01068115234375, 0.029052734375, -0.00634765625, 0.048492431640625, -0.0355224609375, -0.0113067626953125, -0.0244293212890625, 0.040374755859375, 0.0119781494140625, -0.0052642822265625, -0.020355224609375, 0.0097503662109375, -0.0283355712890625, -0.059600830078125, 0.0225830078125, -0.0091552734375, 0.00380706787109375, 0.026275634765625, -0.0278778076171875, 0.0474853515625, 0.038604736328125, -0.0270843505859375, 0.053924560546875, 0.038177490234375, -0.048828125, 0.05157470703125, 0.005596160888671875, 0.0190277099609375, -0.051727294921875, 0.034698486328125, 0.017303466796875, 0.041168212890625, -0.043121337890625, -0.01122283935546875, -0.0291748046875, -0.005764007568359375, 0.018646240234375, 0.019622802734375, -0.05511474609375, 0.05242919921875, 0.0137176513671875, -0.033721923828125, 0.046844482421875, -0.0311279296875, -0.0102691650390625, -0.0276031494140625, -0.0687255859375, 0.03326416015625, 0.034759521484375, 0.0305023193359375, -0.0083465576171875, -0.026702880859375, -0.008026123046875, 0.048095703125, 0.024688720703125, 0.002536773681640625, 0.0269317626953125, 0.02850341796875, 0.0164947509765625, 0.053558349609375, 0.010162353515625, -0.016998291015625, 0.017852783203125, 0.0221405029296875, -0.004878997802734375, 0.0064849853515625, 0.029449462890625, 0.01198577880859375, 0.0216217041015625, 0.0140533447265625, -0.03485107421875, 0.0266876220703125, 0.0136871337890625, 0.007633209228515625, 0.0082855224609375, 0.0238800048828125, 0.0212860107421875, -0.0026264190673828125, -0.0203094482421875, -0.0537109375, 0.0133056640625, -0.0111846923828125, 0.0259857177734375, -0.09747314453125, 0.036468505859375, -0.01009368896484375, -0.042724609375, 0.035186767578125, -0.009979248046875, 0.016693115234375, -0.0012102127075195312, -0.010772705078125, -0.0165863037109375, -0.04534912109375, 0.01024627685546875, -0.049652099609375, 0.05029296875, 0.04327392578125, -0.00934600830078125, 0.0277099609375, -0.028350830078125, -0.022674560546875, -0.04718017578125, -0.033935546875, -0.01277923583984375, -0.01094818115234375, 0.0304718017578125, -0.001483917236328125, -0.060394287109375, -0.042694091796875, 0.0281982421875, 0.034088134765625, 0.0211029052734375, -0.008453369140625, 0.0023822784423828125, -0.0081634521484375, 0.0014324188232421875, 0.0186767578125, 0.0255279541015625, 0.022613525390625, -0.0289764404296875, 0.03704833984375, -0.0135040283203125, -0.01117706298828125, -0.025482177734375, -0.01030731201171875, -0.031707763671875, 0.06353759765625, 0.0103607177734375, 0.00888824462890625, -0.0276336669921875, 0.0235748291015625, -0.01456451416015625, 0.00868988037109375, -0.0012187957763671875, -0.0021820068359375, -0.007549285888671875, -0.0004875659942626953, 0.0157012939453125, -0.038116455078125, -0.0269317626953125, -0.0149993896484375, 0.052520751953125, 0.042205810546875, -0.004261016845703125, -0.027801513671875, -0.01474761962890625, -0.0300445556640625, -0.032623291015625, 0.00954437255859375, 0.051177978515625, 0.004512786865234375, 0.030303955078125, -0.04571533203125, 0.02655029296875, 0.00743865966796875, 0.0225830078125, 0.007373809814453125, 0.001628875732421875, 0.03338623046875, 0.0221405029296875, 0.0202484130859375, -0.028411865234375, -0.037567138671875, -0.0222320556640625, -0.070556640625, 0.01708984375, 0.0185699462890625, -0.043914794921875, 0.0143890380859375, 0.036590576171875, 0.0171051025390625, 0.035491943359375, -0.0111541748046875, 0.045928955078125, -0.02862548828125, 0.0307769775390625, -0.035552978515625, -0.046173095703125, 0.0280609130859375, 0.00864410400390625, -0.00409698486328125, 0.030670166015625, 0.04913330078125, -0.01430511474609375, -0.01385498046875, 0.03515625, -0.04986572265625, 0.039154052734375, -0.03619384765625, 0.01512908935546875, -0.025665283203125, -0.0269012451171875, -0.00787353515625, -0.044036865234375, 0.037109375, 0.0186767578125, 0.03155517578125, -0.03057861328125, -0.060089111328125, -0.01064300537109375, -0.0059967041015625, -0.0131683349609375, 0.0001665353775024414, 0.0009765625, 0.0054473876953125, -0.014862060546875, -0.0274505615234375, -0.0216217041015625, -0.021759033203125, -0.005252838134765625, 0.0186309814453125, -0.04583740234375, 0.0223388671875, 0.00142669677734375, -0.0008134841918945312, -0.003021240234375, -0.001590728759765625, 0.0024929046630859375, -0.0221710205078125, -0.037322998046875, 0.0236053466796875, -0.032623291015625, 0.016845703125, -0.036224365234375, 0.034637451171875, -0.03143310546875, 0.0687255859375, 0.027587890625, 0.0179443359375, 0.01151275634765625, -0.0087432861328125, -0.046630859375, 0.0374755859375, -0.005947113037109375, -0.031829833984375, -0.0281524658203125, 0.050323486328125, -0.0367431640625, 0.03863525390625, 0.00396728515625, -0.0170440673828125, -0.07305908203125, -0.04229736328125, -0.002994537353515625, -0.041351318359375, -0.02740478515625, -0.0355224609375, -0.0026569366455078125, -0.0165252685546875, 0.049835205078125, 0.0036602020263671875, 0.0085906982421875, -0.01454925537109375, -0.0190887451171875, -0.0181732177734375, -0.0199432373046875, -0.0350341796875, -0.032318115234375, 0.008697509765625, 0.0035858154296875, 0.0328369140625, 0.0009555816650390625, 0.05377197265625, 0.0079193115234375, 0.03515625, 0.0249786376953125, -0.03302001953125, -0.037261962890625, -0.0213775634765625, -7.802248001098633e-05, -0.0191650390625, -0.006683349609375, 0.021697998046875, -0.06781005859375, 0.024078369140625, -0.0452880859375, 0.0261383056640625, -0.0234832763671875, -0.01071929931640625, -0.01197052001953125, -0.016845703125, 0.06585693359375, -0.015716552734375, -0.0250244140625, -0.0264129638671875, 0.0416259765625, 0.071044921875, 0.0003056526184082031, -0.041839599609375, -0.00489044189453125, -0.0284576416015625, -0.05364990234375, 0.02960205078125, -0.029205322265625, -0.033660888671875, -0.08062744140625, 0.00937652587890625, 0.023345947265625, 0.004730224609375, 0.0112762451171875, 0.048736572265625, -0.00795745849609375, -0.031951904296875, -0.01128387451171875, 0.01824951171875, 0.041656494140625, -0.0211029052734375, -0.0146636962890625, -0.02215576171875, -0.0109710693359375, -0.00875091552734375, -0.050048828125, -0.05401611328125, -0.058990478515625, -0.004741668701171875, 0.08056640625, -0.035125732421875, 0.045928955078125, 0.006252288818359375, -0.0731201171875, -0.05035400390625, 0.03607177734375, -0.01117706298828125, 0.001270294189453125, 0.05810546875, -0.016357421875, -0.0399169921875, -0.01557159423828125, 0.04718017578125, -0.038604736328125, -0.018646240234375, 0.06414794921875, -0.021240234375, -0.04461669921875, 0.04595947265625, 0.048095703125, -0.044708251953125, -0.0667724609375, 0.004673004150390625, -0.002010345458984375, 0.025909423828125, -0.033111572265625, -0.0128173828125, -0.029296875, 0.005420684814453125, 0.0295257568359375, 0.0254364013671875, -0.0236358642578125, 0.0233154296875, 0.026580810546875, 0.01227569580078125, -0.051116943359375, 0.032928466796875, 0.01502227783203125, -0.00650787353515625, -0.0298309326171875, -0.02606201171875, 0.0299224853515625, -0.0165252685546875, -0.03314208984375, 0.03131103515625, -0.01537322998046875, -0.00749969482421875, 0.0274505615234375, -0.01007080078125, 0.0190277099609375, 0.01326751708984375, 0.00018477439880371094, -0.031982421875, -0.0297088623046875, -0.04156494140625, -0.05084228515625, 0.00855255126953125, -0.0190277099609375, 0.0169677734375, -0.0467529296875, 0.0008916854858398438, 0.0081787109375, -0.0171051025390625, 0.0003809928894042969, -0.0474853515625, -0.0258026123046875, -0.044281005859375, -0.0268096923828125, -0.0195770263671875, 0.025146484375, 0.0283050537109375, 0.049957275390625, 0.032196044921875, -0.027923583984375, -0.0172882080078125, -0.0055084228515625, -0.01477813720703125, -0.0164947509765625, -0.055419921875, 0.01678466796875, -0.005420684814453125, -0.0382080078125, -0.03741455078125, 0.018951416015625, -0.0205841064453125, -0.020111083984375, -0.01861572265625, 0.00179290771484375, -0.0049591064453125, 0.025177001953125, -0.005489349365234375, -0.0181121826171875, 0.00905609130859375, -0.031005859375, -0.0040740966796875, 0.032867431640625, -0.002025604248046875, 0.065185546875, -0.007045745849609375, -0.0306243896484375, 0.02685546875, -0.020843505859375, -0.02838134765625, -0.0036449432373046875, 0.004787445068359375, -0.024810791015625, 0.052215576171875, -0.0279998779296875, -0.036224365234375, -0.044189453125, -0.024505615234375, 0.040283203125, 0.0102691650390625, 0.00968170166015625, -0.03668212890625, 0.021453857421875, 0.009185791015625, 0.061065673828125, -0.00589752197265625, 0.033966064453125, 0.044586181640625, -0.0086517333984375, -0.004146575927734375, -0.0195159912109375, 0.0212860107421875, 0.021759033203125, 0.032379150390625, -0.0305023193359375, -0.00447845458984375, -0.01111602783203125, -0.01064300537109375, 0.048065185546875, -0.0175628662109375, -0.0097198486328125, -0.038177490234375, -0.0091400146484375, -0.0110931396484375, 0.05377197265625, 0.027374267578125, -0.041412353515625, 0.039276123046875, -0.043182373046875, -0.060791015625, -0.0162200927734375, -0.083251953125, 0.01055908203125, 0.04022216796875, -0.0208740234375, -0.0097808837890625, -0.05084228515625, -0.04901123046875, 0.0184783935546875, 0.0186920166015625, 0.005756378173828125, -0.03399658203125, 0.0302734375, -0.0225830078125, 0.05615234375, -0.00836181640625, -0.01177215576171875, -0.0038089752197265625, 0.0667724609375, -0.0269317626953125, -0.008148193359375, 0.01270294189453125, -0.005458831787109375, 0.00028252601623535156, 0.001850128173828125, 0.01476287841796875, 0.03582763671875, 0.0244293212890625, 0.020751953125, -0.003696441650390625, 0.032928466796875, 0.0188140869140625, 0.03350830078125, 0.03857421875, -0.017120361328125, -0.029327392578125, 0.032623291015625, 0.011871337890625, 0.00908660888671875, -0.06396484375, 0.04156494140625, 0.0174407958984375, -0.0286865234375, 0.05322265625, 0.03778076171875, 0.040191650390625, -0.017974853515625, 0.021575927734375, -0.0149993896484375, 0.03070068359375, 0.01430511474609375, 0.02484130859375, 0.00909423828125, 0.01177978515625, 0.040191650390625, -0.00954437255859375, -0.003932952880859375, 0.0214996337890625, 0.02880859375, -0.01172637939453125, 0.0019378662109375, 0.0269775390625, 0.03497314453125, 0.002040863037109375, -0.01004791259765625, -0.004241943359375, -0.006378173828125, -0.0027217864990234375, -0.01448822021484375, 0.01715087890625, 0.041961669921875, -0.0296478271484375, -0.006038665771484375, -0.005771636962890625, -0.0301971435546875, -0.00015604496002197266, 0.0714111328125, 0.009185791015625, 0.0017614364624023438, 0.00472259521484375, -0.028350830078125, -0.0174560546875, 0.03289794921875, 0.036529541015625, -0.002552032470703125, -0.050323486328125, -0.0010700225830078125, 0.03497314453125, -0.0186309814453125, -0.031402587890625, 0.00557708740234375, -0.055206298828125, 0.054718017578125, 0.00283050537109375, 0.005641937255859375, 0.031585693359375, -0.06866455078125, -0.02972412109375, -0.06585693359375, 0.054107666015625, -0.0364990234375, -0.005420684814453125, 0.037261962890625, -0.0151519775390625, -0.0225372314453125, 0.0177154541015625, 0.003871917724609375, 0.055572509765625, -0.0047454833984375, 0.05572509765625, -0.0269012451171875, 0.0251617431640625, 0.042633056640625, -0.0137939453125, -0.00212860107421875, 0.0167694091796875, -0.0026531219482421875, -0.018951416015625, 0.00775146484375, -0.07318115234375, -0.019287109375, -0.0244140625, -0.037445068359375, -0.017913818359375, 0.0297088623046875, -0.0238800048828125, -0.053070068359375, -0.027252197265625, 0.03802490234375, -0.06060791015625, 0.03179931640625, 0.017974853515625, 0.0496826171875, -0.03662109375, -0.0012264251708984375, -0.057373046875, -0.03857421875, 0.01111602783203125, -0.0199432373046875, 0.029205322265625, -0.0297088623046875, 0.0073699951171875, -0.060211181640625, -0.0248260498046875, -0.038238525390625, -0.0157928466796875, -0.0391845703125, -0.05047607421875, 0.07293701171875, 0.043121337890625, 0.001529693603515625, -0.010040283203125, -0.0139617919921875, -0.011016845703125, -0.004581451416015625, 0.053619384765625, -0.00789642333984375, 0.0382080078125, 0.0225372314453125, -0.01348876953125, 0.0296478271484375, -0.025787353515625, 0.02117919921875, -0.006427764892578125, -0.018768310546875, -0.046478271484375, 0.0275115966796875, -0.003284454345703125, -0.05517578125, 0.01120758056640625, 0.00787353515625, 0.01511383056640625, 0.0152740478515625, -0.10101318359375, -0.00942230224609375, -0.046722412109375, 0.022369384765625, -0.0462646484375, 0.031463623046875, -0.0047149658203125, -0.0303802490234375, -0.00647735595703125, -0.0328369140625, 0.1453857421875, 0.0159454345703125, 0.048095703125, 0.02276611328125, -0.009521484375, -0.02423095703125, 0.0234222412109375, -0.014923095703125, 0.023101806640625, 0.0009016990661621094, 0.00902557373046875, -0.0167083740234375, 0.038787841796875, 0.0257110595703125, 0.041351318359375, 0.05755615234375, -0.042236328125, 0.0039825439453125, 0.0013065338134765625, -0.0396728515625, -0.06500244140625, 0.00899505615234375, 0.02325439453125, -0.01436614990234375, -0.00203704833984375, 0.0350341796875, 0.022369384765625, -0.058258056640625, 0.015411376953125, 0.01446533203125, 0.01497650146484375, -0.0227813720703125, 0.048187255859375, -0.026885986328125, -0.01100921630859375, 0.038360595703125, 0.00885772705078125, 0.00927734375, 0.0212860107421875, 0.0168304443359375, -0.01067352294921875, -0.0128326416015625, 0.029632568359375, -0.035430908203125, 0.01641845703125, 0.00559234619140625, -0.039520263671875, -0.0091400146484375, -0.0031185150146484375, -0.035980224609375, 0.0692138671875, -0.033111572265625, 0.00667572021484375, -0.0020503997802734375, -0.052825927734375, 0.0047149658203125, 0.019500732421875, -0.0208740234375, -0.0085296630859375, 0.01245880126953125, 0.05426025390625, -0.00725555419921875, 0.0018863677978515625, -0.0100860595703125, -0.00858306884765625, -0.0206451416015625, 0.0227813720703125, 0.0206451416015625, -0.0100555419921875, 0.0010051727294921875, 0.0160980224609375, 0.00514984130859375, 0.00019633769989013672, -0.0302581787109375, 0.0251312255859375, 0.0259857177734375, -0.016845703125, 0.0180206298828125, 0.01087188720703125, -0.0175018310546875, -0.045135498046875, -0.04547119140625, -0.030731201171875, 0.00514602

In [45]:
print(source_information)

Title: Fight Back to School, Plot: (Cantonese with English subtitles) Classic, slapstick, all-out-ridiculous Hong Kong action-comedy delivered by the one-and-only Stephen Chow (Kung Fu Hustle, Shaolin Soccer), who plays a SWAT team leader going undercover at a high school to retrieve a stolen gun for his captain.
Title: The Last Man, Plot: Apocalyptic comedy finds a socially-challenged grad school student as one of the last two men on Earth with a beautiful woman. However, the other remaining man is his superior in every sense.
Title: The Big Bus, Plot: The ultimate disaster film parody. A nuclear powered bus is going Non-stop from New York to Denver and is plagued by disasters due to the machinations of a mysterious group allied with the Oil lobby. When the driver is injured a washed up, down on his luck, but used to be great type, who as it happens, used to be engaged to the inventor's daughter is brought in to drive the giant bus which includes a one lane swimming pool and a one lane bowling alley.
Title: Shut Up and Kiss Me!, Plot: Ryan and Pete are 27-year old best friends in Miami, born on the same day and each searching for the perfect woman. Ryan is a rookie stockbroker living with his psychic Mom. Pete is a slick surfer dude yet to find commitment. Each meets the women of their dreams on the same day. Ryan knocks heads in an elevator with the gorgeous Jessica, passing out before getting her number. Pete falls for the insatiable Tiara, but Tiara's uncle is mob boss Vincent Bublione, charged with her protection. This high-energy romantic comedy asks to what extent will you go for true love?

In [46]:
combined_information = f"Query: {query}\nContinue to answer the query by using the Search Results:\n{source_information}."

print(combined_information)

Query: what is the best comedy movie to watch and why?
Continue to answer the query by using the Search Results:
Title: Fight Back to School, Plot: (Cantonese with English subtitles) Classic, slapstick, all-out-ridiculous Hong Kong action-comedy delivered by the one-and-only Stephen Chow (Kung Fu Hustle, Shaolin Soccer), who plays a SWAT team leader going undercover at a high school to retrieve a stolen gun for his captain.
Title: The Last Man, Plot: Apocalyptic comedy finds a socially-challenged grad school student as one of the last two men on Earth with a beautiful woman. However, the other remaining man is his superior in every sense.
Title: The Big Bus, Plot: The ultimate disaster film parody. A nuclear powered bus is going Non-stop from New York to Denver and is plagued by disasters due to the machinations of a mysterious group allied with the Oil lobby. When the driver is injured a washed up, down on his luck, but used to be great type, who as it happens, used to be engaged to the inventor's daughter is brought in to drive the giant bus which includes a one lane swimming pool and a one lane bowling alley.
Title: Shut Up and Kiss Me!, Plot: Ryan and Pete are 27-year old best friends in Miami, born on the same day and each searching for the perfect woman. Ryan is a rookie stockbroker living with his psychic Mom. Pete is a slick surfer dude yet to find commitment. Each meets the women of their dreams on the same day. Ryan knocks heads in an elevator with the gorgeous Jessica, passing out before getting her number. Pete falls for the insatiable Tiara, but Tiara's uncle is mob boss Vincent Bublione, charged with her protection. This high-energy romantic comedy asks to what extent will you go for true love?
.

## **Generation**

In [67]:
from google.colab import userdata
HF_KEY=userdata.get('HF_KEY')

In [68]:
from huggingface_hub import login
login(HF_KEY)

In [69]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it", device_map='auto')

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

In [70]:
input_ids=tokenizer(combined_information,return_tensors='pt').to('cuda')

In [73]:
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it", device_map="auto")

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [74]:
response=model.generate(**input_ids,max_new_tokens=500)

In [77]:
response[0].shape

torch.Size([443])

In [78]:
print(tokenizer.decode(response[0]))

<bos>Query: what is the best comedy movie to watch and why?
Continue to answer the query by using the Search Results:
Title: Fight Back to School, Plot: (Cantonese with English subtitles) Classic, slapstick, all-out-ridiculous Hong Kong action-comedy delivered by the one-and-only Stephen Chow (Kung Fu Hustle, Shaolin Soccer), who plays a SWAT team leader going undercover at a high school to retrieve a stolen gun for his captain.
Title: The Last Man, Plot: Apocalyptic comedy finds a socially-challenged grad school student as one of the last two men on Earth with a beautiful woman. However, the other remaining man is his superior in every sense.
Title: The Big Bus, Plot: The ultimate disaster film parody. A nuclear powered bus is going Non-stop from New York to Denver and is plagued by disasters due to the machinations of a mysterious group allied with the Oil lobby. When the driver is injured a washed up, down on his luck, but used to be great type, who as it happens, used to be engaged to the inventor's daughter is brought in to drive the giant bus which includes a one lane swimming pool and a one lane bowling alley.
Title: Shut Up and Kiss Me!, Plot: Ryan and Pete are 27-year old best friends in Miami, born on the same day and each searching for the perfect woman. Ryan is a rookie stockbroker living with his psychic Mom. Pete is a slick surfer dude yet to find commitment. Each meets the women of their dreams on the same day. Ryan knocks heads in an elevator with the gorgeous Jessica, passing out before getting her number. Pete falls for the insatiable Tiara, but Tiara's uncle is mob boss Vincent Bublione, charged with her protection. This high-energy romantic comedy asks to what extent will you go for true love?
.

**The best comedy movie to watch is "Fight Back to School".**

It is a classic slapstick comedy with a unique plot and memorable characters. The movie is perfect for fans of Hong Kong cinema and anyone who enjoys a good laugh.<eos>